### ISSUE TITLE
[1.14.3] Server crash on placing a snowmancy snowman.

### ISSUE THREAD

**Issue by ProsperCraft** [bl4ckscor3/Snowmancy#2] opened 2019-07-08 01:57 UTC
Multiplayer server- player placed one and now the server crashes every time he logs in.

Server Crash
https://paste.fedoraproject.org/paste/B8ZtRxcNbRSVSlsJ3mOn6A

Repeated here-
https://gist.github.com/ProsperCraft/0f83e93ccd38b74ca22f620fff4a0a54

Server logs-
[2019-07-01-2.log.gz](https://github.com/bl4ckscor3/Snowmancy/files/3366409/2019-07-01-2.log.gz)
[debug-1.log.gz](https://github.com/bl4ckscor3/Snowmancy/files/3366410/debug-1.log.gz)
[debug-2.log.gz](https://github.com/bl4ckscor3/Snowmancy/files/3366411/debug-2.log.gz)
[2019-07-01-1.log.gz](https://github.com/bl4ckscor3/Snowmancy/files/3366412/2019-07-01-1.log.gz)

snowmancy-1.14.x-v1.0.1
forge-1.14.3-27.0.25

Modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by ProsperCraft** [comment] 2019-07-08 02:10
Player reports it doesn't crash single player.

So perhaps a sidedness issue.  The new 4 sides sidedness is tripping up most mods.

**Comment by bl4ckscor3** [comment] 2019-07-08 13:09
I cannot reproduce this. I placed down a Snowman Companion with a bow as a weapon and the server did not crash. Same thing happened when placing it down near an enemy - the Snowman Companion attacks the enemy and the server doesn't crash.

**Comment by bl4ckscor3** [comment] 2019-07-18 22:35
Closing as I cannot reproduce this and there hasn't been another reply by you. If you open issues, please do not ghost them and actually try to help with the resolution (I've had this 'no reply'-thing happen with you twice already). Please reopen this issue if you have more information.

**Closed as completed by bl4ckscor3** 2019-07-18 22:35 UTC
